#ifndef FVHMCOMPONENT_GLOBAL_H
#define FVHMCOMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FVHMCOMPONENT_LIBRARY)
#  define FVHMCOMPONENT_EXPORT Q_DECL_EXPORT
#else
#  define FVHMCOMPONENT_EXPORT Q_DECL_IMPORT
#endif

#endif // FVHMCOMPONENT_GLOBAL_H
